/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package epicurus;

import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;



public class App {
    private final TcpServer server;

    @Inject
    public App(TcpServer server) {
        this.server = server;  
    }

    void start() {
        try {
            server.start(4000);
        } catch (Exception e) {
            System.out.println("cant start server ");

        }
    }

    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new Module());
        App app = injector.getInstance(App.class);
        app.start();
    }
}
